---
# Source: korifi/templates/components.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-controllers
  name: korifi-controllers-controller-manager
  namespace: korifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korifi-controllers
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        checksum/config: 31eaf8281c416a9450edf722ef7c938c5047a6c17912b11873c7879c9845a791
      labels:
        app: korifi-controllers
    spec:
      containers:
      - name: manager
        env:
        - name: CONTROLLERSCONFIG
          value: /etc/korifi-controllers-config
        image: "europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/korifi/korifi-controllers:latest"
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        - "--kpack-kubeconfig"
        - "/etc/kpack-remote-config/kubeconfig"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10                
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/korifi-controllers-config
          name: korifi-controllers-config
          readOnly: true
        - mountPath: /etc/kpack-remote-config
          name: remote-config
          readOnly: true      
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: korifi-controllers-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: controllers-webhook-server-cert
      - configMap:
          name: korifi-controllers-config
        name: korifi-controllers-config
      - name: remote-config
        secret:
          defaultMode: 420
          secretName: kpack-kubeconfig # kubeconfig
          items:
            - key: kubeconfig
              path: kubeconfig
